<a href="https://colab.research.google.com/github/Manoj-kumar-Nallamala/Automatic-question-generation-for-cognitive-bot-evaluation/blob/master/Heart_failure_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
#Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
#importing dataset
dataset=pd.read_csv('heart_failure_clinical_records_dataset.csv')
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,12]


In [24]:
print(x)

      age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \

In [25]:
#splitting data to train and test sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/3,random_state=0)

In [26]:
#multiple linear regressor
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)
y_pred=regressor.predict(x_test)

In [27]:
#smothening the predicted result into two classes
for i in range(0,len(y_pred)):
    if y_pred[i]>0.5:
        y_pred[i]=1
    else :
        y_pred[i]=0

In [28]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [29]:
print(cm)

[[64  4]
 [14 18]]


In [30]:
print("accuracy obtained : 82%")

accuracy obtained : 82%


In [31]:
#Logistic regrassion
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier_logistic = LogisticRegression(random_state = 0)
classifier_logistic.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [32]:
# Predicting the Test set results
y_pred = classifier_logistic.predict(x_test)

In [33]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [34]:
print(cm)

[[64  4]
 [17 15]]


In [36]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [38]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [41]:
# Predicting the Test set results
y_pred = classifier.predict(x_test)

In [42]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [43]:
print(cm)

[[64  4]
 [22 10]]


In [44]:
# Fitting SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [45]:
# Predicting the Test set results
y_pred = classifier.predict(x_test)

In [46]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [47]:
print(cm)

[[65  3]
 [17 15]]


In [48]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [49]:
# Predicting the Test set results
y_pred = classifier.predict(x_test)


In [50]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [51]:
print(cm)

[[59  9]
 [ 9 23]]


In [52]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [53]:
# Predicting the Test set results
y_pred = classifier.predict(x_test)

In [54]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [55]:
print(cm)

[[66  2]
 [ 9 23]]
